version: '3.9'

services:
  rasa:
    build: .
    container_name: rasa_streamlit_bot
    ports:
      - "5005:5005"   # Rasa server
      - "8501:8501"   # Streamlit UI
    volumes:
      - .:/app        # Mount current directory inside container
    command: >
      sh -c "rasa run --enable-api --cors '*' &
             streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
